path(pwd, path);
path([pwd '/core/'], path);
path([pwd '/filter/'], path);
path([pwd '/filter/kernel'], path);
path([pwd '/filter/sml'], path);
path([pwd '/utils/'], path);
path([pwd '/plot/'], path);
path([pwd '/report/'], path);
path([pwd '/io/'], path);
path([pwd '/gradient/'], path);
path([pwd '/functions/'], path);
%path('functions/home/jung/matlab/', path);
%path('functions/home/tewon/Matlab/Lewicki/expwrcode/stats', path);
%path('functions/home/lewicki/matlab/oc', path);
%path('functions/home/lewicki/matlab/oc/Images',path);
%path('functions/home/lewicki/matlab/oc/Speech',path);
%path(path,'functions/home/lewicki/matlab/oc/Compression');
%path(path,'functions/home/lewicki/matlab/oc/Images/Data');
%path(path,'functions/home/lewicki/matlab/oc/Speech/Data');
%path(path,'functions/home/lewicki/matlab/toolboxes');
%path(path,'functions/home/lewicki/matlab/toolboxes/kdtlbx/mfiles');
%path(path,'functions/home/lewicki/matlab/toolboxes/actools');
%path(path,'functions/home/lewicki/matlab/miscfuncs');
%path(path,'functions/usr/local/contrib/matlab/scripts/version5');
%path('functions/home/lewicki/matlab/hier', path);
%path('functions/home/tewon/Matlab/Tools', path);
%path('functions/home/tewon/Matlab/Images', path);
%path('functions/home/tewon/Matlab/Tools/tmp', path);
%path('functions/home/tewon/Matlab/Speech', path);
