path('filter/', path);
path('sml/', path);
path('utils/', path);
path('functions/home/jung/matlab/', path);
path('functions/home/tewon/Matlab/Lewicki/expwrcode/stats', path);
path('functions/home/lewicki/matlab/oc', path);
path('functions/home/lewicki/matlab/oc/Images',path);
path('functions/home/lewicki/matlab/oc/Speech',path);
path(path,'functions/home/lewicki/matlab/oc/Compression');
path(path,'functions/home/lewicki/matlab/oc/Images/Data');
path(path,'functions/home/lewicki/matlab/oc/Speech/Data');
path(path,'functions/home/lewicki/matlab/toolboxes');
path(path,'functions/home/lewicki/matlab/toolboxes/kdtlbx/mfiles');
path(path,'functions/home/lewicki/matlab/toolboxes/actools');
path(path,'functions/home/lewicki/matlab/miscfuncs');
path(path,'functions/usr/local/contrib/matlab/scripts/version5');
path('functions/home/lewicki/matlab/hier', path);
path('functions/home/tewon/Matlab/Tools', path);
path('functions/home/tewon/Matlab/Images', path);
path('functions/home/tewon/Matlab/Tools/tmp', path);
path('functions/home/tewon/Matlab/Speech', path);
path(path,'functions');